---
# tasks file for zmq

- name: Add zeromq3 ppa Ubuntu
  apt_repository: repo='ppa:chris-lea/zeromq' update_cache=yes
  when: ansible_distribution == "Ubuntu"

- name: Install zeromq3 Ubuntu
  apt: pkg={{ item }}  state=installed update_cache=true
  with_items:
    - libzmq3
    - libzmq3-dev
  when: ansible_distribution == "Ubuntu"

- name: Install zeromq3 repo RedHat
  get_url: url=http://download.opensuse.org/repositories/home:/fengshuo:/zeromq/CentOS_CentOS-6/home:fengshuo:zeromq.repo dest=/etc/yum.repos.d/zeromq.repo mode=0440 owner=root group=root
  when: ansible_os_family == "RedHat"

- name: Install zeromq3 RedHat
  yum: name=zeromq state=latest
  when: ansible_os_family == "RedHat"

