---
# tasks file for elasticsearch

# todo: do we want to switch to the oracle JDK?
# https://www.elastic.co/guide/en/elasticsearch/reference/1.4/setup-service.html#_installing_the_oracle_jdk
# possible other configs
# https://github.com/deimosfr/ansible-elasticsearch/blob/master/tasks/main.yml

- name: "add elasticsearch apt signing key Ubuntu"
  apt_key: url='https://packages.elasticsearch.org/GPG-KEY-elasticsearch' state=present
  when: ansible_distribution == "Ubuntu"

- name: "Add the elasticsearch 1.4 repo Ubuntu"
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main' state=present update_cache=yes
  when: ansible_distribution == "Ubuntu"

- name: Install elasticsearch 1.4 Ubuntu
  apt: pkg={{ item }}  state=installed update_cache=true
  with_items:
   - openjdk-7-jre-headless 
   - elasticsearch
  notify: restart elasticsearch
  when: ansible_distribution == "Ubuntu"

- name: "Configure update-rc.d elasticsearch defaults 95 10 Ubuntu"
  command: update-rc.d elasticsearch defaults 95 10
  when: ansible_distribution == "Ubuntu"

- name: "add elasticsearch rpm signing key RedHat"
  rpm_key: key='https://packages.elasticsearch.org/GPG-KEY-elasticsearch' state=present
  when: ansible_os_family == "RedHat"

- name: "Add the elasticsearch 1.4 repo RedHat"
  template: src=elasticsearch.repo.j2 dest=/etc/yum.repos.d/elasticsearch.repo mode=0444
  when: ansible_os_family == "RedHat"

- name: Install elasticsearch 1.4 RedHat
  yum: name={{ item }}  state=installed update_cache=true
  with_items:
   - java-1.7.0-openjdk
   - elasticsearch
  notify: restart elasticsearch
  when: ansible_distribution == "RedHat"

- name: "Configure elasticsearch service RedHat"
  command: chkconfig elasticsearch on
  when: ansible_distribution == "RedHat"
