---
# tasks file for firewall

- ufw: rule=allow port={{ item }} state=enabled
  with_items:
    - 22
    - 443
  tags: ufw
  when: ansible_distribution == "Ubuntu"

- name: Set iptables to autostart on boot
  command: chkconfig iptables on
  when: ansible_os_family == "RedHat"

- name: iptables running
  service: name=iptables state=started
  when: ansible_os_family == "RedHat"

- name: Open iptables ports
  lineinfile: dest=/etc/sysconfig/iptables
              regexp="^-A INPUT -m state --state NEW -m tcp -p tcp --dport {{item.port}} -j ACCEPT$"
              line="-A INPUT -m state --state NEW -m tcp -p tcp --dport {{item.port}} -j ACCEPT"
              insertafter="^-A INPUT -i lo -j ACCEPT$"
  with_items:
    - { port: 22 }
    - { port: 443 }
  when: ansible_os_family == "RedHat"
  notify:
    - restart iptables
