---
- name: Configure localhost as all-in-one
  hosts: localhost
  sudo: True
  vars:
  roles:
    - { role: os-check, tags: role-os-check }
    - { role: firewall, tags: role-firewall }
    - { role: zmq, tags: role-zmq }
    - { role: epel, tags: role-epel }
    - { role: geoipupdate, tags: role-geoipupdate }
    - { role: elasticsearch, tags: role-elasticsearch }
  tasks:
